---
site_name: "Waldiez"
site_description: "Make AI Agents Collaborate: Drag, Drop, and Orchestrate with Waldiez"
site_url: https://docs.waldiez.io
repo_name: waldiez/waldiez
repo_url: https://github.com/waldiez/waldiez
copyright: "Copyright &copy; 2024 - 2025 Waldiez"
docs_dir: src
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: custom-light
      accent: blue
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: custom-dark
      accent: blue
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # - announce.dismiss
    # - content.action.edit
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - toc.follow
    - toc.integrate
  logo: static/images/waldie.svg
  favicon: static/favicon.ico
  include_sidebar: true
  extra:
    homepage: https://docs.waldiez.io

markdown_extensions:
  - toc:
      permalink: true
      baselevel: 2
  - attr_list
  - markdown.extensions.codehilite:
      guess_lang: true
  - admonition
  - codehilite
  - extra
  - mdx_truly_sane_lists
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - https://fonts.googleapis.com/css2?family=Fredoka:wght@300..700&display=swap
  - static/css/main.css

plugins:
  - search:
      lang: en
  - minify_html
  - open-in-new-tab
  - privacy
  - offline
  - mkdocs-jupyter
  - tags
  - blog:
      blog_dir: blog
      archive: false
      blog_toc: true

nav:
  - Home: index.md
  - Getting Started:
      - Getting Started: usage/index.md
      - Models: usage/models.md
      - Skills: usage/skills.md
      - Agents: usage/agents.md
      - Flow: usage/flow.md
      - Run: usage/run.md
      - Convert: usage/convert.md
  - Examples:
      - Examples: examples/index.md
      - Standup Comedians: examples/1.md
      - Onboarding: examples/2.md
      - Reflection: examples/3.md
      - Tool Use: examples/4.md
      - Coding: examples/5.md
      - Planning: examples/6.md
      - RAG: examples/7.md
      - ReAct: examples/8.md
  - Get Involved:
      - Contribute: contribute/index.md
  - "Playground 🛝": https://waldiez.github.io
  - Blog:
      - Blog: blog/index.md

not_in_nav: |
  CODE_OF_CONDUCT.md
  static/On-boarding.ipynb
